### ISSUE TITLE
Deployed Web App giving error

### ISSUE THREAD

**Issue by william-vw** [gjacob2010/BPMN-Google-Sheets#1]
On the final step, in the generated web app, after selecting "no" and "yes" respectively and clicking "load", the page keeps showing the loading animation. In the developer console, I notice the following errors:
```
Uncaught ReferenceError: M is not defined
    <anonymous> https://n-tix76vivzas4oinbdbrndza3mdbwsfyzgqk46mi-0lu-script.googleusercontent.com/userCodeAppPanel:41
```
And
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://script.google.com/macros/s/AKfycbyai3z4GYmQeivkwfqMjQWtEySrYbf9vOoSIkOP55T_cOzotsFfpoT8-W6ZmEbmXRRtzQ/exec. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 200.
```

See here for the generated google sheet:
https://docs.google.com/spreadsheets/d/1fu4QrM-VR3YICy7ULP_e6L2cYrrwiUGJf1LDAo3XIRg/edit?usp=sharing

(I think I followed the steps correctly..)

**Comment by gjacob2010** [comment]
Hi William:
Sorry about that glitch.  I have fixed it now.  It seems like when I use
parallel gateways in this app, it gives me that error that will be fixed.

I have put another bpmn file to try which only has exclusive gateways.  If
you go to the github page https://github.com/gjacob2010/BPMN-Google-Sheets
it should work now.  The only two differences from the previous
instructions are:
1) I have changed the bpmn example file to only contain exclusive gateways
2) I have taken away the step to share the newly created google sheet
before you create the app.  It seems to throw the CORS error.

Please let me know if this works.  Seems to be working fine for me now.

Thanks
George
